// src/app/terms/page.tsx — CREATE NEW

export const metadata = {
  title: 'Terms of Service - EduExplorer',
  description: 'EduExplorer Terms of Service - Rules and guidelines for using our platform',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-sm p-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>

        <div className="prose prose-gray max-w-none space-y-6">
          
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using EduExplorer, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Description of Service</h2>
            <p className="text-gray-700 leading-relaxed">
              EduExplorer is an AI-powered educational platform that provides:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>AI-generated educational content on any topic</li>
              <li>Interactive quizzes and flashcards</li>
              <li>Progress tracking and learning analytics</li>
              <li>Study groups and social learning features</li>
              <li>Notifications via WhatsApp and SMS</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. User Accounts</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              To use EduExplorer, you must:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Be at least 13 years old</li>
              <li>Provide accurate and complete information during signup</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized account access</li>
              <li>Be responsible for all activities under your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Phone Number Verification</h2>
            <p className="text-gray-700 leading-relaxed">
              By signing up, you consent to receive OTP verification codes via WhatsApp or SMS. These messages are essential for account security and cannot be opted out of. You may opt out of promotional notifications in your profile settings.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Acceptable Use</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              You agree NOT to:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Use the service for any illegal purpose</li>
              <li>Share copyrighted content without permission</li>
              <li>Harass, abuse, or harm other users</li>
              <li>Attempt to hack, reverse engineer, or compromise the platform</li>
              <li>Create multiple accounts to abuse free tier limits</li>
              <li>Use automated bots or scrapers</li>
              <li>Share your account with others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Intellectual Property</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              <strong>AI-Generated Content:</strong> Content generated by our AI (articles, quizzes, flashcards) is provided for your personal educational use. You may not republish or commercially distribute AI-generated content.
            </p>
            <p className="text-gray-700 leading-relaxed">
              <strong>Platform Code & Design:</strong> The EduExplorer platform, including its design, code, and branding, is owned by us and protected by copyright laws.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Subscription and Payments</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              <strong>Free Plan:</strong> Limited features available at no cost.
            </p>
            <p className="text-gray-700 leading-relaxed mb-3">
              <strong>Pro Plan:</strong> Paid subscription with advanced features. Payments are processed through Razorpay. By subscribing:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>You authorize recurring monthly charges</li>
              <li>You can cancel anytime (no refunds for partial months)</li>
              <li>Prices may change with 30 days notice</li>
              <li>Failed payments may result in service suspension</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Content Accuracy</h2>
            <p className="text-gray-700 leading-relaxed">
              Our AI generates educational content to the best of its ability, but we do not guarantee 100% accuracy. Content is for educational purposes only and should not be considered professional advice. Always verify critical information from authoritative sources.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Termination</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to suspend or terminate your account if you violate these terms. You may delete your account at any time from your profile settings.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Disclaimer of Warranties</h2>
            <p className="text-gray-700 leading-relaxed">
              EduExplorer is provided "as is" without warranties of any kind. We do not guarantee uninterrupted access, error-free operation, or that the service will meet your specific needs.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">11. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              To the maximum extent permitted by law, EduExplorer shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">12. Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These terms are governed by the laws of India. Any disputes shall be resolved in the courts of [Your City/State], India.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">13. Changes to Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              We may update these Terms of Service from time to time. We will notify you of significant changes via email or WhatsApp. Continued use of the service after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">14. Contact Us</h2>
            <p className="text-gray-700 leading-relaxed">
              For questions about these terms, contact us at:
            </p>
            <div className="bg-gray-50 p-4 rounded-lg mt-3">
              <p className="text-gray-700"><strong>Email:</strong> admin@eduexplorer.ai</p>
              <p className="text-gray-700"><strong>Legal:</strong> admin@eduexplorer.ai</p>
              <p className="text-gray-700"><strong>Address:</strong> [Hyderbad]</p>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}
