import { GoogleGenerativeAI } from '@google/generative-ai';
import { prisma } from '../db/prisma';
import { getCached, setCache } from '../db/redis';

const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;
const genAI = GOOGLE_API_KEY ? new GoogleGenerativeAI(GOOGLE_API_KEY) : null;

console.log('🔑 Research Service - API Key Status:');
console.log('  - GOOGLE_API_KEY:', GOOGLE_API_KEY ? '✅ SET' : '❌ MISSING');

export async function processResearchQuery(
  userId: string,
  queryText: string,
  learningLevel: string
) {
  const cacheKey = `research:${queryText}:${learningLevel}`;
  const cached = await getCached(cacheKey);
  
  if (cached) {
    console.log('✅ Returning cached research');
    return { ...cached, fromCache: true };
  }

  console.log('📝 Creating new research query...');
  
  const query = await prisma.query.create({
    data: {
      userId,
      queryText,
      complexityLevel: learningLevel,
      status: 'processing',
    },
  });

  try {
    console.log('🔍 Researching topic with Google Gemini...');
    const result = await researchTopicWithGemini(queryText, learningLevel);

    await prisma.researchData.create({
      data: {
        queryId: query.id,
        rawData: result as any,
        sources: result.sources as any,
        summary: result.content.substring(0, 500),
      },
    });

    await prisma.query.update({
      where: { id: query.id },
      data: {
        status: 'completed',
        topicDetected: result.topic,
      },
    });

    const response = { queryId: query.id, ...result };
    await setCache(cacheKey, response, 86400);

    console.log('✅ Research completed');
    return response;
  } catch (error) {
    console.error('❌ Research failed:', error);
    await prisma.query.update({
      where: { id: query.id },
      data: { status: 'failed' },
    });
    throw error;
  }
}

async function researchTopicWithGemini(
  query: string,
  learningLevel: string = 'college'
): Promise<any> {
  if (!genAI) {
    throw new Error('GOOGLE_API_KEY not configured');
  }

  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

  const prompt = `You are an educational research assistant. Explain this topic: "${query}"

Target audience: ${learningLevel} level students

Provide a comprehensive explanation covering:
1. Core concepts and definitions
2. Key principles and theories
3. Real-world applications
4. Common misconceptions
5. Related topics for further study

Make it clear, accurate, and engaging for ${learningLevel} level.`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const content = response.text();

    console.log(`✅ Research content generated: ${content.length} characters`);

    // Extract any URLs mentioned as sources (simplified)
    const sources = extractSourcesFromContent(content);

    return {
      content,
      sources,
      topic: query,
      complexity: learningLevel,
    };
  } catch (error: any) {
    console.error('❌ Gemini research error:', error.message);
    throw error;
  }
}

function extractSourcesFromContent(content: string): Array<{ title: string; url: string; snippet: string }> {
  const sources: Array<{ title: string; url: string; snippet: string }> = [];
  const urlRegex = /(https?:\/\/[^\s]+)/g;
  const urls = content.match(urlRegex) || [];
  
  urls.forEach((url, index) => {
    sources.push({
      title: `Reference ${index + 1}`,
      url,
      snippet: 'Source referenced in research',
    });
  });

  // If no URLs found, add a generic educational source reference
  if (sources.length === 0) {
    sources.push({
      title: 'Generated with Google Gemini',
      url: 'https://ai.google.dev/',
      snippet: 'Educational content generated by AI',
    });
  }

  return sources;
}
